INFO 11:16:54  当前执行的appium相关配置为：{'platformName': 'Android', 'platformVersion': '6.0', 'deviceName': '192.168.56.101:5555', 'udid': '192.168.56.101:5555', 'systemPort': 8201, 'app': '/Users/jm-yf/PycharmProjects/appauto/apk/jumei_xiaomi_7305.apk', 'clearSystemFiles': True, 'appActivity': 'com.jm.android.jumei.home.activity.StartActivity', 'appPackage': 'com.jm.android.jumei', 'automationName': 'UIAutomator2', 'noSign': True, 'recreateChromeDriverSessions': True, 'unicodeKeyboard': 'True', 'noReset': True, 'fullReset': False, 'newCommandTimeout': 100} 

INFO 11:16:54  Could not connect to port 4723 on host 172.20.11.11 

INFO 11:16:54  Could not get IP address for host: 172.20.11.11 

WARNING 11:16:54  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b486208>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session 

WARNING 11:16:54  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b486438>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session 

WARNING 11:16:54  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b486588>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session